# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  churchlude-benchmarks:
    dependencies:
    - base
    - churchlude
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
category: Other
description: Churchlude is a church encoding based custom Prelude
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: Strikingwolf/churchlude
library:
  dependencies:
  - base
  source-dirs: library
license: MIT
maintainer: Strikingwolf
name: churchlude
synopsis: A new Haskeleton package.
tests:
  churchlude-test-suite:
    dependencies:
    - base
    - churchlude
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
default-extensions:
  - RankNTypes
  - NoImplicitPrelude
  - TypeOperators
  - ConstraintKinds
